Add status to kni-operator custom resource
mhrivnak/kni-operator pull request #3
Opened 2019-06-10 18:03 UTC by djzager

Adding one condition type to make it easy to recognize when the
reconcile has completed successfully. Also, when we find objects that we
have created, add them to the RelatedObjects for auditing objects
created by this operator.

2019-07-07 03:55 UTC, mhrivnak requested changes

2019-07-07 03:55 UTC, mhrivnak commented on pkg/apis/kni/v1alpha1/knicluster_status.go
> +type ObjectReference struct {
How about using this instead? https://github.com/kubernetes/kubernetes/blob/v1.14.3/staging/src/k8s.io/api/core/v1/types.go#L4538

2019-07-07 03:55 UTC, mhrivnak commented on pkg/apis/kni/v1alpha1/knicluster_status.go
> +	ConditionStatusUnknown ConditionStatus = "Unkown"
s/Unkown/Unknown/

2019-07-07 03:55 UTC, mhrivnak commented on pkg/apis/kni/v1alpha1/knicluster_status.go
> +func RemoveCondition(conditions *[]Condition, conditionType ConditionType) {
Fun golang trick. You can do this approximately like so:

```
for i, condition := range conditions {
	if condition.Type == conditionType {
		return append(conditions[:i], conditions[i+1:]...)
	}
}
return conditions
```

2019-07-07 03:55 UTC, mhrivnak commented on pkg/controller/knicluster/knicluster_controller.go
> +	_ = r.client.Status().Update(context.TODO(), instance)
Not checking the error?

2019-07-07 03:55 UTC, mhrivnak commented on pkg/controller/knicluster/knicluster_controller.go
> +			_ = r.client.Status().Update(context.TODO(), instance)
Not checking the error?

2019-07-09 16:51 UTC, djzager commented
I need to re-implement this knowing what I know now from the CVO status.Conditions. Will create another PR (and hopefully remember to include your comments).

2019-07-09 16:51 UTC, closed without merging